### ISSUE TITLE
Exception : "tag 3C is not supported"

### ISSUE THREAD

**Issue by plefebvre91** [Riscure/python-trsfile#5]
Hello,

I got the following problem when I tried to run the example code to read a TRS file.

I thought it was a problem of encoding. Originally I tried to read a `ISO 8859-1` encoded file. Then I converted it to `utf-8`, but got the same exception.

Any idea ?

The backtrace:

```python
Traceback (most recent call last):
  File "./read.py", line 3, in <module>
    with trsfile.open('example.trs', 'r', encoding='utf-8') as traces:
  File "/home/plefebvre/trs/lib/python3.8/site-packages/trsfile/__init__.py", line 41, in trs_open
    return TraceSet(path, mode, **options)
  File "/home/plefebvre/trs/lib/python3.8/site-packages/trsfile/trace_set.py", line 51, in __init__
    self.engine = engine(path, mode, **options)
  File "/home/plefebvre/trs/lib/python3.8/site-packages/trsfile/engine/trs.py", line 135, in __init__
    self.__initialize_headers(headers)
  File "/home/plefebvre/trs/lib/python3.8/site-packages/trsfile/engine/trs.py", line 334, in __initialize_headers
    self.__read_headers()
  File "/home/plefebvre/trs/lib/python3.8/site-packages/trsfile/engine/trs.py", line 474, in __read_headers
    raise NotImplementedError('Warning: tag {tag:02X} is not supported by the library, please submit an issue on Github.'.format(tag=tag))
NotImplementedError: Warning: tag 3C is not supported by the library, please submit an issue on Github.
```

**Comment by johan-riscure** [comment]
How have you created/obtained the .trs file? Because 3C is indeed an invalid tag, so this suggests an invalid file.

Notably, character 3C corresponds to the less-than sign `<` in both ISO 8859-1 and UTF-8, so this makes me wonder if you perhaps accidentally saved an HTML or XML file as .trs?

**Comment by plefebvre91** [comment]
Ok, I'm a retarded, there is not only 1 TRS format in this world and this is not the one I wanted :sweat_smile: 

Thanks !
